services:
  zookeeper:
    image: bitnami/zookeeper:latest
    platform: linux/amd64
    container_name: bda_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:latest
    platform: linux/amd64
    container_name: bda_kafka
    depends_on: [zookeeper]
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports: ["9092:9092"]
